<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Явная ссылка на проект Server.Core -->
    <ProjectReference Include="..\Server.Core\Server.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Пакет для работы с SQLite -->
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
  </ItemGroup>

</Project>
