<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- Явно указываем корневое пространство имен -->
    <RootNamespace>Server.Core</RootNamespace>
  </PropertyGroup>

</Project>